#ifndef _GECKONATOR_USART_H
#define _GECKONATOR_USART_H

enum usart_flags {
	USART_FLAG_COLLISION       = USART_IF_CCF,
	USART_FLAG_SLAVE           = USART_IF_SSM,
	USART_FLAG_MP_ADDRESS      = USART_IF_MPAF,
	USART_FLAG_FRAMING_ERROR   = USART_IF_FERR,
	USART_FLAG_PARITY_ERROR    = USART_IF_PERR,
	USART_FLAG_TX_UNDERFLOW    = USART_IF_TXUF,
	USART_FLAG_TX_OVERFLOW     = USART_IF_TXOF,
	USART_FLAG_RX_UNDERFLOW    = USART_IF_RXUF,
	USART_FLAG_RX_OVERFLOW     = USART_IF_RXOF,
	USART_FLAG_RX_FULL         = USART_IF_RXFULL,
	USART_FLAG_RX_VALID        = USART_IF_RXDATAV,
	USART_FLAG_TX_BUFFER_LEVEL = USART_IF_TXBL,
	USART_FLAG_TX_COMPLETE     = USART_IF_TXC,
};

#endif
